import { Router, Request, Response } from 'express';

const router = Router();

const APP_NAME = process.env.APP_NAME ?? 'SMS Food Journal';
const APP_URL = process.env.APP_URL ?? '';
const CONTACT_EMAIL = process.env.CONTACT_EMAIL ?? 'support@example.com';

router.get('/privacy', (_req: Request, res: Response) => {
  res.type('html').send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Privacy Policy – ${APP_NAME}</title>
  <style>
    body { font-family: sans-serif; max-width: 680px; margin: 48px auto; padding: 0 24px; line-height: 1.6; color: #222; }
    h1 { font-size: 1.8rem; } h2 { font-size: 1.2rem; margin-top: 2rem; }
  </style>
</head>
<body>
  <h1>Privacy Policy</h1>
  <p><strong>Last updated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</strong></p>

  <h2>1. Information We Collect</h2>
  <p>We collect your phone number when you subscribe, and the meal descriptions you send us via SMS.</p>

  <h2>2. How We Use Your Information</h2>
  <p>We use your phone number solely to send you meal logging confirmations and daily nutrition summaries. We do not use your information for marketing or share it with third parties.</p>

  <h2>3. SMS Messaging</h2>
  <p>By subscribing, you consent to receive SMS messages from ${APP_NAME}, including meal confirmations and daily nutrition summaries. Message frequency varies based on your usage (typically 1–10 messages per day). <strong>Message and data rates may apply.</strong> Reply STOP at any time to unsubscribe. Reply HELP for help.</p>

  <h2>4. No Sharing of Mobile Numbers</h2>
  <p>We will not share, sell, rent, or trade your mobile phone number with any third party for their marketing purposes.</p>

  <h2>5. Data Retention</h2>
  <p>We retain your meal logs for as long as your account is active. You may request deletion by contacting us.</p>

  <h2>6. Contact</h2>
  <p>Questions? Email us at <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a></p>
</body>
</html>`);
});

router.get('/terms', (_req: Request, res: Response) => {
  res.type('html').send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Terms of Service – ${APP_NAME}</title>
  <style>
    body { font-family: sans-serif; max-width: 680px; margin: 48px auto; padding: 0 24px; line-height: 1.6; color: #222; }
    h1 { font-size: 1.8rem; } h2 { font-size: 1.2rem; margin-top: 2rem; }
  </style>
</head>
<body>
  <h1>Terms of Service</h1>
  <p><strong>Last updated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</strong></p>

  <h2>1. Service</h2>
  <p>${APP_NAME} is an SMS-based food journaling service. Users text meal descriptions to our number and receive estimated nutrition information in return, along with a daily summary.</p>

  <h2>2. Subscription</h2>
  <p>Access requires an active paid subscription. Subscriptions are billed as described at checkout and managed via Stripe.</p>

  <h2>3. SMS Consent & Opt-Out</h2>
  <p>By subscribing you consent to receive SMS messages from ${APP_NAME}. <strong>Message and data rates may apply.</strong> You can opt out at any time by replying STOP to any message. Reply HELP for support.</p>

  <h2>4. Nutrition Information</h2>
  <p>Nutrition estimates are generated by AI and are approximate. They are not medical advice. Consult a qualified professional for dietary guidance.</p>

  <h2>5. Limitation of Liability</h2>
  <p>${APP_NAME} is provided "as is." We are not liable for inaccuracies in nutrition data or any damages arising from use of the service.</p>

  <h2>6. Contact</h2>
  <p>Questions? Email us at <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a></p>
</body>
</html>`);
});

export default router;
